grails-app/domain/org/afdb/rs/VisiteForm.groovy
package org.afdb.rs

import java.util.Date;
import java.util.Formatter.DateTime

import org.afdb.Staff;

class VisiteForm {
	
	Staff 	receiverVisit
	Staff	askBy
	
	Staff	approvedBy
	Staff	declinedBy
	Staff	canceledBy
	
	String	company
	String	event
	String	purposeOfVisite
	
	Date	expectedArrivingDateTime
	Date 	expectedDepartureDateTime
	
	Integer	visitDuration
	
	VisitStatus	status
	VisitType	visitType
	Location	location
	
	/* Automatic timestamping of GORM */
	Date	dateCreated
	Date	lastUpdated

//	static	belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static	hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
	static	hasMany		= [visitors:Visitor]	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static	mappedBy	= []	// specifies which property should be used in a mapping
		
	static	mapping = {
	}
	
    static constraints = {
		receiverVisit	nullable:true
		askBy()
		
		approvedBy	nullable:true
		declinedBy	nullable:true
		canceledBy	nullable:true
		
		status()
		visitType()
		location()
		
		company	nullable:true
		event	nullable:true
		purposeOfVisite		nullable:true, maxSize:3076
		
		expectedArrivingDateTime(nullable:true)
		expectedDepartureDateTime(nullable:true)
		visitDuration(nullable:true)
		
		dateCreated	nullable:true
		lastUpdated	nullable:true
    }
}

grails-app/views/visiteForm - copie/_form.gsp
<%@ page import="org.afdb.rs.VisiteForm" %>



			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'surname', 'error')}">
				<label for="surname" class="control-label"><g:message code="visiteForm.surname.label" default="Surname" /></label>
				<div class="controls ">
					<g:textField class="form-control" name="surname" value="${visiteFormInstance?.surname}" />
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'surname', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'firstname', 'error')} ">
				<label for="firstname" class="control-label"><g:message code="visiteForm.firstname.label" default="Firstname" /></label>
				<div class="controls">
					<g:textField class="form-control" name="firstname" value="${visiteFormInstance?.firstname}"/>
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'firstname', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'address', 'error')} ">
				<label for="address" class="control-label"><g:message code="visiteForm.address.label" default="Address" /></label>
				<div class="controls">
					<g:textField class="form-control" name="address" value="${visiteFormInstance?.address}"/>
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'address', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'profession', 'error')} ">
				<label for="profession" class="control-label"><g:message code="visiteForm.profession.label" default="Profession" /></label>
				<div class="controls">
					<g:textField class="form-control" name="profession" value="${visiteFormInstance?.profession}"/>
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'profession', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'wantToSee', 'error')} required">
				<label for="wantToSee" class="control-label"><g:message code="visiteForm.wantToSee.label" default="Want To See" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:select class="form-control" id="wantToSee" name="wantToSee.id" from="${org.afdb.Staff.list()}" optionKey="id" required="" value="${visiteFormInstance?.wantToSee?.id}" class="many-to-one"/>
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'wantToSee', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'purposeOfVisite', 'error')} ">
				<label for="purposeOfVisite" class="control-label"><g:message code="visiteForm.purposeOfVisite.label" default="Purpose Of Visite" /></label>
				<div class="controls">
					<g:textArea class="form-control" rows="3" name="purposeOfVisite" value="${visiteFormInstance?.purposeOfVisite}"/>
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'purposeOfVisite', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'expectedArrivingDateTime', 'error')} required">
				<label for="expectedArrivingDateTime" class="control-label"><g:message code="visiteForm.expectedArrivingDateTime.label" default="Expected Arriving Date Time" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<bs:datePicker class="form-control" name="expectedArrivingDateTime" precision="day"  value="${visiteFormInstance?.expectedArrivingDateTime}"  />
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'expectedArrivingDateTime', 'error')}</span>
				</div>
			</div>
	
			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'actualArrivingDateTime', 'error')} required">
				<label for="actualArrivingDateTime" class="control-label"><g:message code="visiteForm.actualArrivingDateTime.label" default="Actual Arriving Date Time" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<bs:datePicker name="actualArrivingDateTime" precision="day"  value="${visiteFormInstance?.actualArrivingDateTime}"  />
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'actualArrivingDateTime', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: visiteFormInstance, field: 'departureTime', 'error')} required">
				<label for="departureTime" class="control-label"><g:message code="visiteForm.departureTime.label" default="Departure Time" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<bs:datePicker name="departureTime" precision="day"  value="${visiteFormInstance?.departureTime}"/>
					<span class="help-inline">${hasErrors(bean: visiteFormInstance, field: 'departureTime', 'error')}</span>
				</div>
			</div>

grails-app/views/visiteForm - copie/create.gsp
<%@ page import="org.afdb.rs.VisiteForm" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visiteForm.label', default: 'VisiteForm')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
			<g:set var="layout_nomainmenu"		value="${true}" scope="request"/>
	
</head>

<body>

<section id="create-visiteForm" class="first">

	<g:hasErrors bean="${visiteFormInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${visiteFormInstance}" as="list" />
	</div>
	</g:hasErrors>
	
	<g:form action="save" class="form-horizontal" >
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
		</div>
	</g:form>
	
</section>
		
</body>

</html>

grails-app/views/visiteForm - copie/edit.gsp
<%@ page import="org.afdb.rs.VisiteForm" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visiteForm.label', default: 'VisiteForm')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
		<g:set var="layout_nomainmenu"		value="${true}" scope="request"/>
	
</head>

<body>

<section id="edit-visiteForm" class="first">

	<g:hasErrors bean="${visiteFormInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${visiteFormInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${visiteFormInstance?.id}" />
		<g:hiddenField name="version" value="${visiteFormInstance?.version}" />
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
			<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
		</div>
	</g:form>

</section>
			
</body>

</html>

grails-app/views/visiteForm - copie/list.gsp
<%@ page import="org.afdb.rs.VisiteForm" %>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visiteForm.label', default: 'VisiteForm')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
	<g:set var="layout_nomainmenu"		value="${true}" scope="request"/>
	
</head>

<body>
	
<section id="list-visiteForm" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
			<tr>
			
				<g:sortableColumn property="surname" title="${message(code: 'visiteForm.surname.label', default: 'Surname')}" />
				
				<g:sortableColumn property="firstname" title="${message(code: 'visiteForm.firstname.label', default: 'Firstname')}" />
				<g:sortableColumn property="expectedArrivingDateTime" title="${message(code: 'visiteForm.expectedArrivingDateTime.label', default: 'Expected Arriving time')}" />
				<g:sortableColumn property="actualArrivingDateTime" title="${message(code: 'visiteForm.actualArrivingDateTime.label', default: 'Actual Arriving time')}" />
			
				<g:sortableColumn property="address" title="${message(code: 'visiteForm.address.label', default: 'Address')}" />				
			
				<g:sortableColumn property="profession" title="${message(code: 'visiteForm.profession.label', default: 'Profession')}" />
			
				<th><g:message code="visiteForm.wantToSee.label" default="Want To See" /></th>
			
				<g:sortableColumn property="purposeOfVisite" title="${message(code: 'visiteForm.purposeOfVisite.label', default: 'Purpose Of Visite')}" />
				<th>Action</th>
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${visiteFormInstanceList}" status="i" var="visiteFormInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td>${fieldValue(bean: visiteFormInstance, field: "surname")}</td>
			
				<td>${fieldValue(bean: visiteFormInstance, field: "firstname")}</td>
				<td>${fieldValue(bean: visiteFormInstance, field: "expectedArrivingDateTime")}</td>
				
				<td>${fieldValue(bean: visiteFormInstance, field: "actualArrivingDateTime")}</td>
				
			
				<td>${fieldValue(bean: visiteFormInstance, field: "address")}</td>
			
				<td>${fieldValue(bean: visiteFormInstance, field: "profession")}</td>
			
				<td>${fieldValue(bean: visiteFormInstance, field: "wantToSee")}</td>
			
				<td>${fieldValue(bean: visiteFormInstance, field: "purposeOfVisite")}</td>
				<td><g:link class="btn btn-primary" action="show" id="${visiteFormInstance.id}">Open</g:link></td>
				
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="container">
		<bs:paginate total="${visiteFormInstanceTotal}" />
	</div>
</section>

</body>

</html>

grails-app/views/visiteForm - copie/show.gsp
<%@ page import="org.afdb.rs.VisiteForm" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visiteForm.label', default: 'VisiteForm')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
			<g:set var="layout_nomainmenu"		value="${true}" scope="request"/>
	
</head>

<body>

<section id="show-visiteForm" class="first">

	<table class="table">
		<tbody>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.surname.label" default="Surname" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: visiteFormInstance, field: "surname")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.firstname.label" default="Firstname" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: visiteFormInstance, field: "firstname")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.address.label" default="Address" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: visiteFormInstance, field: "address")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.profession.label" default="Profession" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: visiteFormInstance, field: "profession")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.wantToSee.label" default="Want To See" /></td>
				
				<td valign="top" class="value"><g:link controller="staff" action="show" id="${visiteFormInstance?.wantToSee?.id}">${visiteFormInstance?.wantToSee?.encodeAsHTML()}</g:link></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.purposeOfVisite.label" default="Purpose Of Visite" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: visiteFormInstance, field: "purposeOfVisite")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.expectedArrivingDateTime.label" default="Expected Arriving Date Time" /></td>
				
				<td valign="top" class="value"><g:formatDate date="${visiteFormInstance?.expectedArrivingDateTime}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.actualArrivingDateTime.label" default="Actual Arriving Date Time" /></td>
				
				<td valign="top" class="value"><g:formatDate date="${visiteFormInstance?.actualArrivingDateTime}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="visiteForm.departureTime.label" default="Departure Time" /></td>
				
				<td valign="top" class="value"><g:formatDate date="${visiteFormInstance?.departureTime}" /></td>
				
			</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>