grails-app/domain/org/afdb/rs/Visitor.groovy
package org.afdb.rs

import org.afdb.*

/**
 * Visitor
 * A domain class describes the data object and it's mapping to the database
 */
class Visitor {

	/* Default (injected) attributes of GORM */
//	Long	id
//	Long	version
	
	String	firstName
	String	lastName
	String	gender
	static String MALE="M"
	static String FEMALE="F"
	
	String	address
	String	contact
	
	String	typeOfCard
	static final String PC="PC"
	static final String CNI="CNI"
	static final String PASSPORT="PASSPORT"
	static final String LAISSEZPASSER="LAISSEZPASSER"
	static final String CARTECONSULAIRE="CARTECONSULAIRE"
	static final String OTHER="OTHER"
	
	String	otherCard
	String	numberCard
	Date	validityDate
//	Integer	badgeNumber
	
//	VisitorStatus	status
	VisiteForm	visit
	VisitType	visitType
	
	Date	checkinGateDate
//	Date	checkoutDateTime
	
//	User	deniedGateBy
//	User	entryPermitBy
	
//	Staff	deniedReceptionBy
//	Staff	checkinBy
	
//	Staff	checkoutBy
	
//	String	deniedGate
//	String 	deniedReception
	
	/* Automatic timestamping of GORM */
	Date	dateCreated
	Date	lastUpdated
	
//	static	belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static	hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
	static	hasMany		= [entrys:VisitorEntry]	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static	mappedBy	= []	// specifies which property should be used in a mapping 
	
    static	mapping = {
    }
    
	static	constraints = {
		firstName()
		lastName()
		gender(inList:[MALE,FEMALE])
		
		address	nullable:true
		contact nullable:true
		
		typeOfCard	nullable:true
		otherCard	nullable:true
		numberCard	nullable:true
		validityDate	nullable:true
		
		visit	nullable:true
		visitType	nullable:true
		
		checkinGateDate	nullable:true
		/*
		status()
		
		badgeNumber nullable:true
		
		checkinDateTime		nullable:true
		checkoutDateTime	nullable:true
		
		deniedGateBy		nullable:true
		entryPermitBy		nullable:true
		deniedReceptionBy	nullable:true
		checkinBy			nullable:true
		checkoutBy			nullable:true
		
		deniedGate			nullable:true, maxSize:1024
		deniedReception		nullable:true, maxSize:1024
		*/
    }
	
	/*
	 * Methods of the Domain Class
	 */
	@Override	// Override toString for a nicer / more descriptive UI 
	public String toString() {
		return "${firstName} ${lastName}, ${gender}";
	}
}

grails-app/domain/org/afdb/rs/VisitorEntry.groovy
package org.afdb.rs

import java.util.Date;

import org.afdb.Staff;
import org.afdb.User;

/**
 * VisitorEntry
 * A domain class describes the data object and it's mapping to the database
 */
class VisitorEntry {

	/* Default (injected) attributes of GORM */
//	Long	id
//	Long	version
	
	Visitor	visitor
	VisitorStatus	status
	
	Date	checkinDateTime
	Date	checkoutDateTime
	
	User	deniedGateBy
	User	entryPermitBy
	
	Staff	deniedReceptionBy
	Staff	checkinBy
	
	Staff	checkoutBy
	
	String	deniedGate
	String 	deniedReception
	
	TypeBadge	badge
	Integer		badgeNumber
	
	
	/* Automatic timestamping of GORM */
	Date	dateCreated
	Date	lastUpdated
	
//	static	belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static	hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
//	static	hasMany		= []	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static	mappedBy	= []	// specifies which property should be used in a mapping 
	
    static	mapping = {
    }
    
	static	constraints = {
		visitor()
		status()
		
		badge		nullable:true
		badgeNumber	nullable:true
		
		checkinDateTime		nullable:true
		checkoutDateTime	nullable:true
		
		deniedGateBy		nullable:true
		entryPermitBy		nullable:true
		deniedReceptionBy	nullable:true
		checkinBy			nullable:true
		checkoutBy			nullable:true
		
		deniedGate			nullable:true, maxSize:1024
		deniedReception		nullable:true, maxSize:1024
    }
	
	/*
	 * Methods of the Domain Class
	 */
//	@Override	// Override toString for a nicer / more descriptive UI 
//	public String toString() {
//		return "${name}";
//	}
}

grails-app/views/visitor/_form.gsp
<%@ page import="org.afdb.rs.Visitor" %>

<g:set var="lang" value="${session.'org.springframework.web.servlet.i18n.SessionLocaleResolver.LOCALE' ?: org.springframework.web.servlet.support.RequestContextUtils.getLocale(request).toString().substring(0,2)}"/>

	<div class="row">
		
		<div class="col-md-12">
			<h1 class="center">${message(code:'visitor.title', default:'Visitor')}</h1>
			<br/>
		</div>
		
	</div>
	
	<div class="row">
	
		<div class="col-md-6">
			
			<div class="panel panel-default">
				<div class="panel-body form-horizontal payment-form">
			
					<div class="form-group">
						<label for="firstName" class="col-sm-4 control-label"><g:message code="visitor.firstName.label" default="First Name" /></label>
						<div class="col-sm-8">
							<g:textField class="form-control" name="firstName" value="${visitorInstance?.firstName}"/>
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'firstName', 'error')}</span>
						</div>
					</div>
					
					<div class="form-group">
						<label for="lastName" class="col-sm-4 control-label"><g:message code="visitor.lastName.label" default="Last Name" /></label>
						<div class="col-sm-8">
							<g:textField class="form-control" name="lastName" value="${visitorInstance?.lastName}"/>
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'lastName', 'error')}</span>
						</div>
					</div>
					
					<div class="form-group">
						<label for="gender" class="col-sm-4 control-label"><g:message code="visitor.gender.label" default="Gender" /></label>
						<div class="col-sm-8">
							<g:select class="form-control" name="gender" 
								from="${visitorInstance.constraints.gender.inList}"
								value="${visitorInstance?.gender}"
								valueMessagePrefix="visitor.gender"
								style="width:30%;" noSelection="['': '']" />
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'gender', 'error')}</span>
						</div>
					</div>
		
					<div class="form-group">
						<label for="address" class="col-sm-4 control-label"><g:message code="visitor.address.label" default="Address" /></label>
						<div class="col-sm-8">
							<g:textField class="form-control" name="address" value="${visitorInstance?.address}"/>
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'address', 'error')}</span>
						</div>
					</div>
		
					<div class="form-group">
						<label for="contact" class="col-sm-4 control-label"><g:message code="visitor.contact.label" default="Contact" /></label>
						<div class="col-sm-8">
							<g:textField class="form-control" name="contact" value="${visitorInstance?.contact}"/>
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'contact', 'error')}</span>
						</div>
					</div>
				
				</div>
			</div>
		
		</div>
		
		<div class="col-md-6">
			
			<div class="panel panel-default">
				<div class="panel-body form-horizontal payment-form">
					
					<div class="form-group">
						<label for="contact" class="col-sm-4 control-label"><g:message code="visitType.label" default="Contact" /></label>
						<div class="col-sm-8">
							<g:visitType type="${visitorInstance?.visit?.visitType}"/>
						</div>
					</div>
					
					<div class="form-group">
						<label for="badgeNumber" class="col-sm-4 control-label"><g:message code="visitorEntry.badgeNumber.label" default="Badge Number" /></label>
						<div class="col-sm-8">
							<div class="row">
								<div class="col-sm-6">
									<g:select class="form-control" 
										id="badge" name="badge.id" 
										from="${org.afdb.rs.TypeBadge.list()}"
										optionKey="id" required=""
										value="${visitorEntryInstance?.badge?.id}"
										optionValue="${{it?.getName(lang.toString())}}"
										onChange="toggle('#testDiv', this)"
										style="width:100%;" noSelection="${[null:'Select Type of Badge']}" />
								</div>
								<div class="col-sm-6">
									<g:field class="form-control" type="number" name="badgeNumber" value="${visitorEntryInstance?.badgeNumber}" style="width:100%;"/>
									<span class="help-inline">${hasErrors(bean: visitorEntryInstance, field: 'badgeNumber', 'error')}</span>
								</div>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<label for="typeOfCard" class="col-sm-4 control-label"><g:message code="visitor.typeOfCard.label" default="Type Of Card" /></label>
						<div class="col-sm-8">
							<g:select class="form-control"  name="typeOfCard" 
								from="${listOptionTypeOfCard}" 
								noSelection="${[null:'Select One...']}" 
								value="${fieldValue(bean: visitorInstance, field: 'typeOfCard')}" 
								valueMessagePrefix="visitor.typeOfCard" 
								onChange="toggle('#testDiv', this)"
								style="width:70%;"/>
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'typeOfCard', 'error')}</span>
						</div>
					</div>
					
					<div id="idOtherCard">
						<div class="form-group">
							<label for="otherCard" class="col-sm-4 control-label"><g:message code="visitor.otherCard.label" default="Other Card (Specify)" /></label>
							<div class="col-sm-8">
								<g:textField class="form-control" name="otherCard" value="${visitorInstance?.otherCard}"/>
								<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'otherCard', 'error')}</span>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<label for="numberCard" class="col-sm-4 control-label"><g:message code="visitor.numberCard.label" default="Number of Card" /></label>
						<div class="col-sm-8">
							<g:textField class="form-control" name="numberCard" value="${visitorInstance?.numberCard}"/>
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'numberCard', 'error')}</span>
						</div>
					</div>
					
					<div class="form-group">
						<label for="validityDate" class="col-sm-4 control-label"><g:message code="visitor.validityDate.label" default="Validity Date" /></label>
						<div class="col-sm-8">
							<bs:datePicker name="validityDate" precision="day"  value="${visitorInstance?.validityDate}" default="none" noSelection="['': '']" />
							<span class="help-inline">${hasErrors(bean: visitorInstance, field: 'validityDate', 'error')}</span>
						</div>
					</div>
										
				</div>
			</div>
			
		</div>
		
		<g:hiddenField  value="${visitorInstance?.visit?.id}" id="visit" name="visit.id" />
		<g:hiddenField  value="${visitorEntryInstance?.id}" id="entry" name="entry.id" />
		
	</div>

			

grails-app/views/visitor/_listEvent.gsp
<%@ page import="org.afdb.rs.Visitor" %>
<%@ page import="org.afdb.rs.VisitorStatus" %>

	<table class="table table-bordered margin-top-medium">
		<tbody>
		<g:each in="${visitors}" status="i" var="visitorInstance">
			<g:if test="${(visitorInstance?.checkinGateDate==null) || (formatDate(format:'yyyy-MM-dd', date:visitorInstance?.checkinGateDate) != formatDate(format:'yyyy-MM-dd', date:currentDay))}">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				<td>
					<div class="row">
						<div class="col-md-10">
							<strong>${visitorInstance?.lastName} ${visitorInstance?.firstName}</strong>
							<br/>
							Gender:	<strong>${visitorInstance?.gender}</strong>
							<%--
							<br/> 
							Status: <g:visitorStatus status="${visitorInstance?.status}"/>
							--%>
						</div>
						<div class="col-md-2">
							<div class="col-md-3">
								<g:form method="post" class="form-horizontal" action="entrance" name="submitForm">
									<g:hiddenField  value="${visitorInstance?.id}" id="visitor" name="visitor.id" />
															
									<button type="submit" class="btn btn-sm btn-success" id="validateId" onClick="pleaseWait(this);">
										<i class="glyphicon glyphicon-ok"></i>
										<span id="idOK">
										</span>	
									</button>
									
								</g:form>
							</div>
							<%--
							<div class="col-md-3">
								<g:form method="post" class="form-horizontal" action="repressedGate">
									<g:hiddenField  value="${visitorInstance?.id}" id="visitor" name="visitor.id" />
															
									<g:if test="${visitorInstance?.status?.code in [VisitorStatus.AWAITING]}">				
										<button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('${message(code: 'default.button.reset.submission.confirm.message', default: 'Are you sure?')}');">
											<i class="glyphicon glyphicon-remove"></i>
										</button>
									</g:if>
									<g:else>
										<button type="submit" disabled="disabled" class="btn btn-sm btn-danger">
											<i class="glyphicon glyphicon-remove"></i>
										</button>
									</g:else>
								</g:form>
							</div>
							--%>
							<div class="col-md-3">
								<g:link class="btn btn-sm btn-danger" controller="${params.controller}" action="showGate" id="${visitorInstance.id}">
									<i class="glyphicon glyphicon-remove"></i>
								</g:link>
							</div>
							
						</div>
					</div>
					
				</td>			
			</tr>
			</g:if>
		</g:each>
		</tbody>
	</table>
	
	<%-- 
	<div class="container">
		<bs:paginate total="${visitorInstanceTotal}" />
	</div>
	--%>

grails-app/views/visitor/_listGate.gsp
<%@ page import="org.afdb.rs.Visitor" %>
<%@ page import="org.afdb.rs.VisitorStatus" %>

	<table class="table table-bordered margin-top-medium">
		<tbody>
		<g:each in="${visitorInstanceList}" status="i" var="visitorInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				<td>
					<div class="row">
						<div class="col-md-10">
							<strong>${visitorInstance?.lastName} ${visitorInstance?.firstName}</strong>
							<br/>
							Gender:	<strong>${visitorInstance?.gender}</strong>
							<%--
							<br/> 
							Status: <g:visitorStatus status="${visitorInstance?.status}"/>
							--%>
						</div>
						<div class="col-md-2">
							<div class="col-md-3">
								<g:form method="post" class="form-horizontal" action="entrance" name="submitForm">
									<g:hiddenField  value="${visitorInstance?.id}" id="visitor" name="visitor.id" />
															
									<button type="submit" class="btn btn-sm btn-success" id="validateId" onClick="pleaseWait(this);">
										<i class="glyphicon glyphicon-ok"></i>
										<span id="idOK">
										</span>	
									</button>
									
								</g:form>
							</div>
							<%--
							<div class="col-md-3">
								<g:form method="post" class="form-horizontal" action="repressedGate">
									<g:hiddenField  value="${visitorInstance?.id}" id="visitor" name="visitor.id" />
															
									<g:if test="${visitorInstance?.status?.code in [VisitorStatus.AWAITING]}">				
										<button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('${message(code: 'default.button.reset.submission.confirm.message', default: 'Are you sure?')}');">
											<i class="glyphicon glyphicon-remove"></i>
										</button>
									</g:if>
									<g:else>
										<button type="submit" disabled="disabled" class="btn btn-sm btn-danger">
											<i class="glyphicon glyphicon-remove"></i>
										</button>
									</g:else>
								</g:form>
							</div>
							--%>
							<div class="col-md-3">
								<g:link class="btn btn-sm btn-danger" controller="${params.controller}" action="showGate" id="${visitorInstance.id}">
									<i class="glyphicon glyphicon-remove"></i>
								</g:link>
							</div>
							
						</div>
					</div>
					
				</td>			
			</tr>
		</g:each>
		</tbody>
	</table>
	
	<%-- 
	<div class="container">
		<bs:paginate total="${visitorInstanceTotal}" />
	</div>
	--%>

grails-app/views/visitor/list.gsp
<%@ page import="org.afdb.rs.Visitor" %>

<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
	<g:set var="layout_nosecondarymenu"	value="${true}" scope="request"/>
</head>

<body>

<g:render template="/_menu/menuVisitForm"/>

<section id="list-visitor" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
			<tr>
				<g:sortableColumn property="firstName" title="${message(code: 'visitor.firstName.label', default: 'First Name')}" />
				<g:sortableColumn property="lastName" title="${message(code: 'visitor.lastName.label', default: 'Last Name')}" />
				<g:sortableColumn property="gender" title="${message(code: 'visitor.gender.label', default: 'Gender')}" />
				<g:sortableColumn property="address" title="${message(code: 'visitor.address.label', default: 'Address')}" />
				<g:sortableColumn property="contact" title="${message(code: 'visitor.contact.label', default: 'Contact')}" />
				<%--
				<g:sortableColumn property="company" title="${message(code: 'visitor.company.label', default: 'Company')}" />
				--%>
			</tr>
		</thead>
		<tbody>
		<g:each in="${visitorInstanceList}" status="i" var="visitorInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${visitorInstance.id}">${fieldValue(bean: visitorInstance, field: "firstName")}</g:link></td>
			
				<td>${fieldValue(bean: visitorInstance, field: "lastName")}</td>
			
				<td>${fieldValue(bean: visitorInstance, field: "gender")}</td>
			
				<td>${fieldValue(bean: visitorInstance, field: "address")}</td>
			
				<td>${fieldValue(bean: visitorInstance, field: "contact")}</td>
				<%-- 
				<td>${fieldValue(bean: visitorInstance, field: "company")}</td>
			--%>
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="container">
		<bs:paginate total="${visitorInstanceTotal}" />
	</div>
</section>

</body>

</html>

grails-app/views/visitor/listDesk.gsp
<%@ page import="org.afdb.rs.Visitor" %>
<%@ page import="org.afdb.rs.VisitorStatus" %>

<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
	<g:set var="layout_nosecondarymenu"	value="${true}" scope="request"/>
</head>

<body>

<g:render template="/_menu/menuVisitForm"/>

<section id="list-visitor" class="first">
	
	<table class="table table-bordered margin-top-medium">
		<tbody>
		<g:each in="${visitorEntryInstanceList}" status="i" var="visitorEntryInstance">
			<g:set var="visitorInstance" value="${Visitor?.get(visitorEntryInstance?.visitor?.id)}"/>
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				<td>
					<div class="row">
						<div class="col-md-10">
							<strong>${visitorInstance?.lastName} ${visitorInstance?.firstName}</strong>
							<br/>
							Gender:	<strong>${visitorInstance?.gender}</strong>
							<br/>
							Status: <g:visitorStatus status="${visitorEntryInstance?.status}"/>
						</div>
						<div class="col-md-2">
							<div class="col-md-3">
								<g:form method="post" class="form-horizontal" action="checkin" name="submitForm">
									<g:hiddenField  value="${visitorEntryInstance?.id}" id="entry" name="entry.id" />
															
									<g:if test="${visitorEntryInstance?.status?.code in [VisitorStatus.ENTRANCE]}">			
										<button type="submit" class="btn btn-sm btn-success" id="validateId" onClick="pleaseWait(this);">
											<i class="glyphicon glyphicon-ok"></i>
											<span id="idOK">
											</span>	
										</button>
									</g:if>
									<g:else>
										<button type="submit" disabled="disabled" class="btn btn-sm btn-success">
											<i class="glyphicon glyphicon-ok"></i>
										</button>
									</g:else>
								</g:form>
							</div>
							<%-- 
							<div class="col-md-3">
								<g:form method="post" class="form-horizontal" action="repressedReception">
									<g:hiddenField  value="${visitorInstance?.id}" id="visitor" name="visitor.id" />
															
									<g:if test="${visitorInstance?.status?.code in [VisitorStatus.ENTRANCE]}">				
										<button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('${message(code: 'default.button.reset.submission.confirm.message', default: 'Are you sure?')}');">
											<i class="glyphicon glyphicon-remove"></i>
										</button>
									</g:if>
									<g:else>
										<button type="submit" disabled="disabled" class="btn btn-sm btn-danger">
											<i class="glyphicon glyphicon-remove"></i>
										</button>
									</g:else>
								</g:form>
							</div>
							--%>
							<div class="col-md-3">
								<g:link class="btn btn-sm btn-danger" controller="${params.controller}" action="showDesk" id="${visitorInstance.id}" params="[entryId: visitorEntryInstance?.id]">
									<i class="glyphicon glyphicon-remove"></i>
								</g:link>
							</div>
						</div>
					</div>
					
				</td>			
			</tr>
		</g:each>
		</tbody>
	</table>
	 
	<div class="container">
		<bs:paginate total="${visitorInstanceTotal}" />
	</div>
	
</section>

</body>

</html>

grails-app/views/visitor/showDesk.gsp
<%@ page import="org.afdb.rs.Visitor" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
	<g:set var="layout_nosecondarymenu"	value="${true}" scope="request"/>
</head>

<body>

<g:render template="/_menu/menuVisitForm"/>

<section id="show-visitor" class="first">
	
	<div class="row">
	
		<div class="col-md-6">
	
			<table class="table">
				<tbody>
				
					<tr class="prop">
						<td valign="top" class="name"><g:message code="visitor.firstName.label" default="First Name" /></td>
						<td valign="top" class="value">
							<strong>${fieldValue(bean: visitorInstance, field: "firstName")}</strong>
						</td>
					</tr>
				
					<tr class="prop">
						<td valign="top" class="name"><g:message code="visitor.lastName.label" default="Last Name" /></td>
						<td valign="top" class="value">
							<strong>${fieldValue(bean: visitorInstance, field: "lastName")}</strong>
						</td>
					</tr>
				
					<tr class="prop">
						<td valign="top" class="name"><g:message code="visitor.gender.label" default="Gender" /></td>
						<td valign="top" class="value">
							<strong>${fieldValue(bean: visitorInstance, field: "gender")}</strong>
						</td>
					</tr>
							
				</tbody>
			</table>
		
		</div>
		
		<div class="col-md-6">
			
			<g:form method="post" class="form-horizontal" >
			
				<div class="${hasErrors(bean: visitorEntryInstance, field: 'deniedReception', 'error')} ">
					<label for="deniedReception" class="pull-left"><g:message code="remark.deniedReception.label" default="Remark" /></label>
					<div>
						<g:textArea class="form-control" name="deniedReception" maxlength="1024" cols="50" rows="10" value="${visitorEntryInstance?.deniedReception}"/>
						<span class="help-inline">${hasErrors(bean: visitorEntryInstance, field: 'deniedReception', 'error')}</span>
					</div>
				</div>	
				
				<g:hiddenField  value="${visitorEntryInstance?.id}" id="entry" name="entry.id" />
		
				<div class="form-actions">
					<g:actionSubmit class="btn btn-sm btn-danger" action="deniedDesk" value="${message(code: 'button.denied.label', default: 'Denied')}" />
				</div>
						
			</g:form>
			
		</div>
	
	</div>
							
</section>

</body>

</html>

grails-app/views/visitor/showGate.gsp
<%@ page import="org.afdb.rs.Visitor" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
	<g:set var="layout_nosecondarymenu"	value="${true}" scope="request"/>
</head>

<body>

<g:render template="/_menu/menuVisitForm"/>

<section id="show-visitor" class="first">
	
	<div class="row">
	
		<div class="col-md-6">
	
			<table class="table">
				<tbody>
				
					<tr class="prop">
						<td valign="top" class="name"><g:message code="visitor.firstName.label" default="First Name" /></td>
						<td valign="top" class="value">
							<strong>${fieldValue(bean: visitorInstance, field: "firstName")}</strong>
						</td>
					</tr>
				
					<tr class="prop">
						<td valign="top" class="name"><g:message code="visitor.lastName.label" default="Last Name" /></td>
						<td valign="top" class="value">
							<strong>${fieldValue(bean: visitorInstance, field: "lastName")}</strong>
						</td>
					</tr>
				
					<tr class="prop">
						<td valign="top" class="name"><g:message code="visitor.gender.label" default="Gender" /></td>
						<td valign="top" class="value">
							<strong>${fieldValue(bean: visitorInstance, field: "gender")}</strong>
						</td>
					</tr>
							
				</tbody>
			</table>
		
		</div>
		
		<div class="col-md-6">
			
			<g:form method="post" class="form-horizontal" action="deniedGate">
			
				<div class="${hasErrors(bean: visitorEntryInstance, field: 'deniedGate', 'error')} ">
					<label for="deniedGate" class="pull-left"><g:message code="remark.deniedGate.label" default="Remark" /></label>
					<div>
						<g:textArea class="form-control" name="deniedGate" maxlength="1024" cols="50" rows="10" value="${visitorEntryInstance?.deniedGate}"/>
						<span class="help-inline">${hasErrors(bean: visitorEntryInstance, field: 'deniedGate', 'error')}</span>
					</div>
				</div>	
				
				<g:hiddenField  value="${visitorInstance?.id}" id="visitor" name="visitor.id" />
		
				<div class="form-actions">
					<g:actionSubmit class="btn btn-sm btn-danger" action="deniedGate" value="${message(code: 'button.denied.label', default: 'Denied')}" />
				</div>
						
			</g:form>
			
		</div>
	
	</div>
							
</section>

</body>

</html>